### ISSUE TITLE
Peer Invalid Warning

### ISSUE THREAD

**Issue by shortstuffsushi** [pichalite/nodebb-theme-material-old#1]
Hi there. I was interested in checking out your project, but I ran into a problem when trying to install this with a basic, fresh install of NodeBB. As of [this dependency change](https://github.com/pichalite/nodebb-theme-material/commit/f7057d82b1733368f0390718d8984bfeb2e3909f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L25), your design is incompatible with `nodebb-plugin-spam-be-gone` and `nodebb-theme-lavender` which are pinned with NodeBB itself, and require `nodebb-theme-vanilla` < 1.0.0. Specifically, the error is:

```
npm ERR! peerinvalid The package nodebb-theme-vanilla does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nodebb-plugin-spam-be-gone@0.4.0 wants nodebb-theme-vanilla@>=0.0.137
npm ERR! peerinvalid Peer nodebb-theme-lavender@0.2.13 wants nodebb-theme-vanilla@^0.2.0
npm ERR! peerinvalid Peer nodebb-theme-material@0.1.4 wants nodebb-theme-vanilla@^1.0.0
```

Would you consider bumping back down, or do you have any alternative suggestions?

**Comment by pichalite** [comment]
@shortstuffsushi  What version of NodeBB are you using?

**Comment by shortstuffsushi** [comment]
I am using 0.6.1, which I installed via npm, I believe. Just follow the docs on their site. Also confirmed that is the latest available on npmjs.org.

**Comment by pichalite** [comment]
Uninstall nodebb-theme-material and

Install it from the admin control panel by going to Extend -> Plugins

or use 

npm install nodebb-theme-material@0.0.9

**Comment by shortstuffsushi** [comment]
Sure, I've already done as much (using 0.0.9), but I was asking more about plans for the future, or how to handle potentially less technical users. The docs you have listed for this (`npm install ...`) won't work for a standard install at this point.

**Comment by pichalite** [comment]
The best way to install any plugins for NodeBB is from the admin control panel.

This happens with any theme for Nodebb, not just this one. nodebb-theme-lavender for example installs a specific version even though there is a latest version available in npm because it gets which version to install from package.json of your nodebb installation.

If you remove the dependency from package.json and run (`npm install nodebb-theme-lavender`), you run in to the same issue.

I would be happy to update the docs if you have any suggestion.

**Comment by shortstuffsushi** [comment]
Ah, the latest lavender does indeed use that later version of vanilla, which would cause the same problem. So how do any of these themes expect things to work then? You can't just do a clean `npm install` of the latest, are they perhaps running on a development version of NodeBB with a more recent version of vanilla?

In terms of suggestions, mine would be to keep your dependencies lined up with NodeBB -- unless I'm mistaken, 0.1.0 of your theme is unusable with a standard copy of NodeBB. I would only update to vanilla 1.0.0 after they have.

**Comment by pichalite** [comment]
Updated installation instructions to install it from the plugins page in NodeBB ACP.

**Comment by shortstuffsushi** [comment]
That'll work. Thanks :+1:
